services:

  gotify_webhook_gateway:

    image: geroldpenz/gotify-webhook-gateway

    build:
      context: .
      dockerfile: Dockerfile

    environment:
      NPM_CONFIG_LOGLEVEL: "verbose"

      GOTIFY_URL: "https://gotify.example.com"
      GOTIFY_CLIENT_TOKEN: "<Client-Token>"
